2021-02-08 20:16:42,438 DEBUG    Entered main
2021-02-08 20:16:42,440 DEBUG    Entered raster2nested_list
2021-02-08 20:16:43,444 DEBUG    Exited  raster2nested_list
2021-02-08 20:16:43,459 DEBUG    Entered check_input
2021-02-08 20:16:43,463 DEBUG    Exited  check_input
2021-02-08 20:16:43,463 DEBUG    Entered check_input
2021-02-08 20:16:43,467 DEBUG    Exited  check_input
2021-02-08 20:16:43,467 DEBUG    Entered check_input
2021-02-08 20:16:43,471 DEBUG    Exited  check_input
2021-02-08 20:16:43,471 DEBUG    Entered check_input
2021-02-08 20:16:43,474 DEBUG    Exited  check_input
2021-02-08 20:16:43,474 DEBUG    Entered check_input
2021-02-08 20:16:43,478 DEBUG    Exited  check_input
2021-02-08 20:16:43,478 DEBUG    Entered check_input
2021-02-08 20:16:43,482 DEBUG    Exited  check_input
2021-02-08 20:16:43,482 DEBUG    Entered calculate_snowmelt
2021-02-08 20:16:43,768 DEBUG    Exited  calculate_snowmelt
2021-02-08 20:16:45,258 DEBUG    Entering env context: <rasterio.env.Env object at 0x000000F797DE7448>
2021-02-08 20:16:45,258 DEBUG    Starting outermost env
2021-02-08 20:16:45,259 DEBUG    No GDAL environment exists
2021-02-08 20:16:45,259 DEBUG    New GDAL environment <rasterio._env.GDALEnv object at 0x000000F7985D1608> created
2021-02-08 20:16:45,259 DEBUG    GDAL_DATA found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\gdal'.
2021-02-08 20:16:45,260 DEBUG    PROJ_LIB found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\proj'.
2021-02-08 20:16:45,260 DEBUG    Started GDALEnv <rasterio._env.GDALEnv object at 0x000000F7985D1608>.
2021-02-08 20:16:45,260 DEBUG    Entered env context: <rasterio.env.Env object at 0x000000F797DE7448>
2021-02-08 20:16:45,260 DEBUG    Sharing flag: 0
2021-02-08 20:16:45,262 DEBUG    Nodata success: 1, Nodata value: nan
2021-02-08 20:16:45,262 DEBUG    Dataset <open DatasetReader name='C:\Users\Mouris\Desktop\Python\Python_Sebastian\Python-Course-Project\Results\Snow_end_month\snow_end_month18_3.tif' mode='r'> is started.
2021-02-08 20:16:45,262 DEBUG    Exiting env context: <rasterio.env.Env object at 0x000000F797DE7448>
2021-02-08 20:16:45,262 DEBUG    Cleared existing <rasterio._env.GDALEnv object at 0x000000F7985D1608> options
2021-02-08 20:16:45,263 DEBUG    Stopped GDALEnv <rasterio._env.GDALEnv object at 0x000000F7985D1608>.
2021-02-08 20:16:45,263 DEBUG    Exiting outermost env
2021-02-08 20:16:45,263 DEBUG    Exited env context: <rasterio.env.Env object at 0x000000F797DE7448>
2021-02-08 20:16:45,263 DEBUG    Entering env context: <fiona.env.Env object at 0x000000F7985D1608>
2021-02-08 20:16:45,263 DEBUG    Starting outermost env
2021-02-08 20:16:45,263 DEBUG    No GDAL environment exists
2021-02-08 20:16:45,263 DEBUG    New GDAL environment <fiona._env.GDALEnv object at 0x000000F797DE7448> created
2021-02-08 20:16:45,263 DEBUG    Logging error handler pushed.
2021-02-08 20:16:45,264 DEBUG    All drivers registered.
2021-02-08 20:16:45,264 DEBUG    GDAL_DATA found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\gdal'.
2021-02-08 20:16:45,264 DEBUG    PROJ_LIB found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\proj'.
2021-02-08 20:16:45,264 DEBUG    Started GDALEnv <fiona._env.GDALEnv object at 0x000000F797DE7448>.
2021-02-08 20:16:45,264 DEBUG    Updated existing <fiona._env.GDALEnv object at 0x000000F797DE7448> with options {}
2021-02-08 20:16:45,264 DEBUG    Entered env context: <fiona.env.Env object at 0x000000F7985D1608>
2021-02-08 20:16:45,264 DEBUG    Got a copy of environment <fiona._env.GDALEnv object at 0x000000F797DE7448> options
2021-02-08 20:16:45,264 DEBUG    Credentialized: {'CHECK_WITH_INVERT_PROJ': True, 'GTIFF_IMPLICIT_JPEG_OVR': False, 'FIONA_ENV': True, 'GDAL_DATA': 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\gdal'}
2021-02-08 20:16:45,265 DEBUG    Exiting env context: <fiona.env.Env object at 0x000000F7985D1608>
2021-02-08 20:16:45,265 DEBUG    Cleared existing <fiona._env.GDALEnv object at 0x000000F797DE7448> options
2021-02-08 20:16:45,266 DEBUG    Stopping GDALEnv <fiona._env.GDALEnv object at 0x000000F797DE7448>.
2021-02-08 20:16:45,266 DEBUG    Error handler popped.
2021-02-08 20:16:45,266 DEBUG    Stopped GDALEnv <fiona._env.GDALEnv object at 0x000000F797DE7448>.
2021-02-08 20:16:45,266 DEBUG    Exiting outermost env
2021-02-08 20:16:45,266 DEBUG    Exited env context: <fiona.env.Env object at 0x000000F7985D1608>
2021-02-08 20:16:45,266 DEBUG    Entering env context: <fiona.env.Env object at 0x000000F7985D1608>
2021-02-08 20:16:45,266 DEBUG    Starting outermost env
2021-02-08 20:16:45,266 DEBUG    No GDAL environment exists
2021-02-08 20:16:45,266 DEBUG    New GDAL environment <fiona._env.GDALEnv object at 0x000000F797DE7448> created
2021-02-08 20:16:45,266 DEBUG    Logging error handler pushed.
2021-02-08 20:16:45,267 DEBUG    All drivers registered.
2021-02-08 20:16:45,267 DEBUG    GDAL_DATA found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\gdal'.
2021-02-08 20:16:45,267 DEBUG    PROJ_LIB found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\proj'.
2021-02-08 20:16:45,267 DEBUG    Started GDALEnv <fiona._env.GDALEnv object at 0x000000F797DE7448>.
2021-02-08 20:16:45,267 DEBUG    Updated existing <fiona._env.GDALEnv object at 0x000000F797DE7448> with options {}
2021-02-08 20:16:45,267 DEBUG    Entered env context: <fiona.env.Env object at 0x000000F7985D1608>
2021-02-08 20:16:45,267 DEBUG    Exiting env context: <fiona.env.Env object at 0x000000F7985D1608>
2021-02-08 20:16:45,267 DEBUG    Cleared existing <fiona._env.GDALEnv object at 0x000000F797DE7448> options
2021-02-08 20:16:45,267 DEBUG    Stopping GDALEnv <fiona._env.GDALEnv object at 0x000000F797DE7448>.
2021-02-08 20:16:45,267 DEBUG    Error handler popped.
2021-02-08 20:16:45,267 DEBUG    Stopped GDALEnv <fiona._env.GDALEnv object at 0x000000F797DE7448>.
2021-02-08 20:16:45,268 DEBUG    Exiting outermost env
2021-02-08 20:16:45,268 DEBUG    Exited env context: <fiona.env.Env object at 0x000000F7985D1608>
2021-02-08 20:16:45,268 DEBUG    Flushed buffer
2021-02-08 20:16:45,268 DEBUG    Stopped session
2021-02-08 20:16:45,268 DEBUG    Entering env context: <fiona.env.Env object at 0x000000F7985D1608>
2021-02-08 20:16:45,268 DEBUG    Starting outermost env
2021-02-08 20:16:45,268 DEBUG    No GDAL environment exists
2021-02-08 20:16:45,268 DEBUG    New GDAL environment <fiona._env.GDALEnv object at 0x000000F797DE7448> created
2021-02-08 20:16:45,268 DEBUG    Logging error handler pushed.
2021-02-08 20:16:45,269 DEBUG    All drivers registered.
2021-02-08 20:16:45,269 DEBUG    GDAL_DATA found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\gdal'.
2021-02-08 20:16:45,269 DEBUG    PROJ_LIB found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\proj'.
2021-02-08 20:16:45,269 DEBUG    Started GDALEnv <fiona._env.GDALEnv object at 0x000000F797DE7448>.
2021-02-08 20:16:45,269 DEBUG    Updated existing <fiona._env.GDALEnv object at 0x000000F797DE7448> with options {}
2021-02-08 20:16:45,269 DEBUG    Entered env context: <fiona.env.Env object at 0x000000F7985D1608>
2021-02-08 20:16:45,269 DEBUG    Got a copy of environment <fiona._env.GDALEnv object at 0x000000F797DE7448> options
2021-02-08 20:16:45,269 DEBUG    Credentialized: {'CHECK_WITH_INVERT_PROJ': True, 'GTIFF_IMPLICIT_JPEG_OVR': False, 'FIONA_ENV': True, 'GDAL_DATA': 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\gdal'}
2021-02-08 20:16:45,270 DEBUG    Exiting env context: <fiona.env.Env object at 0x000000F7985D1608>
2021-02-08 20:16:45,270 DEBUG    Cleared existing <fiona._env.GDALEnv object at 0x000000F797DE7448> options
2021-02-08 20:16:45,270 DEBUG    Stopping GDALEnv <fiona._env.GDALEnv object at 0x000000F797DE7448>.
2021-02-08 20:16:45,270 DEBUG    Error handler popped.
2021-02-08 20:16:45,270 DEBUG    Stopped GDALEnv <fiona._env.GDALEnv object at 0x000000F797DE7448>.
2021-02-08 20:16:45,270 DEBUG    Exiting outermost env
2021-02-08 20:16:45,270 DEBUG    Exited env context: <fiona.env.Env object at 0x000000F7985D1608>
2021-02-08 20:16:45,270 DEBUG    Entering env context: <fiona.env.Env object at 0x000000F7985D1608>
2021-02-08 20:16:45,270 DEBUG    Starting outermost env
2021-02-08 20:16:45,270 DEBUG    No GDAL environment exists
2021-02-08 20:16:45,270 DEBUG    New GDAL environment <fiona._env.GDALEnv object at 0x000000F797DE7448> created
2021-02-08 20:16:45,270 DEBUG    Logging error handler pushed.
2021-02-08 20:16:45,271 DEBUG    All drivers registered.
2021-02-08 20:16:45,271 DEBUG    GDAL_DATA found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\gdal'.
2021-02-08 20:16:45,271 DEBUG    PROJ_LIB found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\proj'.
2021-02-08 20:16:45,271 DEBUG    Started GDALEnv <fiona._env.GDALEnv object at 0x000000F797DE7448>.
2021-02-08 20:16:45,271 DEBUG    Updated existing <fiona._env.GDALEnv object at 0x000000F797DE7448> with options {}
2021-02-08 20:16:45,272 DEBUG    Entered env context: <fiona.env.Env object at 0x000000F7985D1608>
2021-02-08 20:16:45,272 DEBUG    Index: 0
2021-02-08 20:16:45,280 DEBUG    Output nodata value read from file: nan
2021-02-08 20:16:45,280 DEBUG    Output nodata values: [nan]
2021-02-08 20:16:45,280 DEBUG    all_valid: False
2021-02-08 20:16:45,280 DEBUG    mask_flags: ([<MaskFlags.nodata: 8>],)
2021-02-08 20:16:45,282 DEBUG    Sharing flag: 0
2021-02-08 20:16:45,283 DEBUG    Nodata success: 1, Nodata value: nan
2021-02-08 20:16:45,283 DEBUG    Dataset <open DatasetBase name='<VRTDataset rasterXSize="3589" rasterYSize="2743"><SRS>PROJCS["WGS 84 / UTM zone 34N",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",21],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","32634"]]</SRS><GeoTransform>438363.722651493,25.0,0.0,4525499.363685054,0.0,-25.0</GeoTransform><VRTRasterBand band="1" dataType="Float32"><NoDataValue>nan</NoDataValue><ColorInterp>Gray</ColorInterp><ComplexSource><SourceFilename relativeToVRT="1">dummy.tif</SourceFilename><SourceBand>1</SourceBand><SourceProperties BlockXSize="3588" BlockYSize="1" RasterXSize="3589" RasterYSize="2743" dataType="Float32" /><SrcRect xOff="0" xSize="1" yOff="0" ySize="1" /><DstRect xOff="0" xSize="1" yOff="0" ySize="1" /><ScaleRatio>0</ScaleRatio><ScaleOffset>nan</ScaleOffset></ComplexSource><ComplexSource><SourceFilename relativeToVRT="0">C:\Users\Mouris\Desktop\Python\Python_Sebastian\Python-Course-Project\Results\Snow_end_month\snow_end_month18_3.tif</SourceFilename><SourceBand>1</SourceBand><SourceProperties BlockXSize="3588" BlockYSize="1" RasterXSize="3589" RasterYSize="2743" dataType="Float32" /><SrcRect xOff="0" xSize="3588" yOff="0" ySize="2742" /><DstRect xOff="-787.0" xSize="3588.0" yOff="-708.0" ySize="2742.0" /><NODATA>nan</NODATA></ComplexSource></VRTRasterBand></VRTDataset>' mode='r'> is started.
2021-02-08 20:16:45,283 DEBUG    Entering env context: <rasterio.env.Env object at 0x000000F79A8EAD08>
2021-02-08 20:16:45,283 DEBUG    Starting outermost env
2021-02-08 20:16:45,283 DEBUG    No GDAL environment exists
2021-02-08 20:16:45,283 DEBUG    New GDAL environment <rasterio._env.GDALEnv object at 0x000000F79A8EAEC8> created
2021-02-08 20:16:45,284 DEBUG    GDAL_DATA found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\gdal'.
2021-02-08 20:16:45,284 DEBUG    PROJ_LIB found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\proj'.
2021-02-08 20:16:45,284 DEBUG    Started GDALEnv <rasterio._env.GDALEnv object at 0x000000F79A8EAEC8>.
2021-02-08 20:16:45,285 DEBUG    Entered env context: <rasterio.env.Env object at 0x000000F79A8EAD08>
2021-02-08 20:16:45,285 DEBUG    IO window xoff=0.0 yoff=0.0 width=2801.0 height=2034.0
2021-02-08 20:16:45,400 DEBUG    Exiting env context: <rasterio.env.Env object at 0x000000F79A8EAD08>
2021-02-08 20:16:45,401 DEBUG    Cleared existing <rasterio._env.GDALEnv object at 0x000000F79A8EAEC8> options
2021-02-08 20:16:45,401 DEBUG    Stopped GDALEnv <rasterio._env.GDALEnv object at 0x000000F79A8EAEC8>.
2021-02-08 20:16:45,401 DEBUG    Exiting outermost env
2021-02-08 20:16:45,401 DEBUG    Exited env context: <rasterio.env.Env object at 0x000000F79A8EAD08>
2021-02-08 20:16:45,404 DEBUG    Entering env context: <rasterio.env.Env object at 0x000000F79A8EAF48>
2021-02-08 20:16:45,404 DEBUG    Starting outermost env
2021-02-08 20:16:45,404 DEBUG    No GDAL environment exists
2021-02-08 20:16:45,404 DEBUG    New GDAL environment <rasterio._env.GDALEnv object at 0x000000F79A8EAD48> created
2021-02-08 20:16:45,405 DEBUG    GDAL_DATA found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\gdal'.
2021-02-08 20:16:45,405 DEBUG    PROJ_LIB found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\proj'.
2021-02-08 20:16:45,405 DEBUG    Started GDALEnv <rasterio._env.GDALEnv object at 0x000000F79A8EAD48>.
2021-02-08 20:16:45,405 DEBUG    Entered env context: <rasterio.env.Env object at 0x000000F79A8EAF48>
2021-02-08 20:16:45,450 DEBUG    Exiting env context: <rasterio.env.Env object at 0x000000F79A8EAF48>
2021-02-08 20:16:45,450 DEBUG    Cleared existing <rasterio._env.GDALEnv object at 0x000000F79A8EAD48> options
2021-02-08 20:16:45,450 DEBUG    Stopped GDALEnv <rasterio._env.GDALEnv object at 0x000000F79A8EAD48>.
2021-02-08 20:16:45,450 DEBUG    Exiting outermost env
2021-02-08 20:16:45,450 DEBUG    Exited env context: <rasterio.env.Env object at 0x000000F79A8EAF48>
2021-02-08 20:16:45,600 DEBUG    Exiting env context: <fiona.env.Env object at 0x000000F7985D1608>
2021-02-08 20:16:45,600 DEBUG    Cleared existing <fiona._env.GDALEnv object at 0x000000F797DE7448> options
2021-02-08 20:16:45,600 DEBUG    Stopping GDALEnv <fiona._env.GDALEnv object at 0x000000F797DE7448>.
2021-02-08 20:16:45,600 DEBUG    Error handler popped.
2021-02-08 20:16:45,600 DEBUG    Stopped GDALEnv <fiona._env.GDALEnv object at 0x000000F797DE7448>.
2021-02-08 20:16:45,600 DEBUG    Exiting outermost env
2021-02-08 20:16:45,601 DEBUG    Exited env context: <fiona.env.Env object at 0x000000F7985D1608>
2021-02-08 20:16:45,601 DEBUG    Flushed buffer
2021-02-08 20:16:45,601 DEBUG    Stopped session
2021-02-08 20:16:45,666 DEBUG    Exited  main
