2021-02-08 08:28:30,022 DEBUG    Entered main
2021-02-08 08:28:30,023 DEBUG    Entered raster2nested_list
2021-02-08 08:28:31,036 DEBUG    Exited  raster2nested_list
2021-02-08 08:28:31,074 DEBUG    Entered calculate_snowmelt
2021-02-08 08:28:31,375 DEBUG    Exited  calculate_snowmelt
2021-02-08 08:28:32,865 DEBUG    Entering env context: <rasterio.env.Env object at 0x0000005A71091948>
2021-02-08 08:28:32,865 DEBUG    Starting outermost env
2021-02-08 08:28:32,865 DEBUG    No GDAL environment exists
2021-02-08 08:28:32,866 DEBUG    New GDAL environment <rasterio._env.GDALEnv object at 0x0000005A70C7B548> created
2021-02-08 08:28:32,866 DEBUG    GDAL_DATA found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\gdal'.
2021-02-08 08:28:32,866 DEBUG    PROJ_LIB found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\proj'.
2021-02-08 08:28:32,867 DEBUG    Started GDALEnv <rasterio._env.GDALEnv object at 0x0000005A70C7B548>.
2021-02-08 08:28:32,867 DEBUG    Entered env context: <rasterio.env.Env object at 0x0000005A71091948>
2021-02-08 08:28:32,867 DEBUG    Sharing flag: 0
2021-02-08 08:28:32,869 DEBUG    Nodata success: 1, Nodata value: nan
2021-02-08 08:28:32,869 DEBUG    Dataset <open DatasetReader name='C:\Users\Mouris\Desktop\Python\Python_Sebastian\Python-Course-Project\Results\Snow_end_month\snow_end_month18_1.tif' mode='r'> is started.
2021-02-08 08:28:32,869 DEBUG    Exiting env context: <rasterio.env.Env object at 0x0000005A71091948>
2021-02-08 08:28:32,870 DEBUG    Cleared existing <rasterio._env.GDALEnv object at 0x0000005A70C7B548> options
2021-02-08 08:28:32,870 DEBUG    Stopped GDALEnv <rasterio._env.GDALEnv object at 0x0000005A70C7B548>.
2021-02-08 08:28:32,870 DEBUG    Exiting outermost env
2021-02-08 08:28:32,870 DEBUG    Exited env context: <rasterio.env.Env object at 0x0000005A71091948>
2021-02-08 08:28:32,870 DEBUG    Entering env context: <fiona.env.Env object at 0x0000005A70C7B548>
2021-02-08 08:28:32,870 DEBUG    Starting outermost env
2021-02-08 08:28:32,870 DEBUG    No GDAL environment exists
2021-02-08 08:28:32,870 DEBUG    New GDAL environment <fiona._env.GDALEnv object at 0x0000005A71091948> created
2021-02-08 08:28:32,870 DEBUG    Logging error handler pushed.
2021-02-08 08:28:32,871 DEBUG    All drivers registered.
2021-02-08 08:28:32,871 DEBUG    GDAL_DATA found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\gdal'.
2021-02-08 08:28:32,871 DEBUG    PROJ_LIB found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\proj'.
2021-02-08 08:28:32,871 DEBUG    Started GDALEnv <fiona._env.GDALEnv object at 0x0000005A71091948>.
2021-02-08 08:28:32,871 DEBUG    Updated existing <fiona._env.GDALEnv object at 0x0000005A71091948> with options {}
2021-02-08 08:28:32,871 DEBUG    Entered env context: <fiona.env.Env object at 0x0000005A70C7B548>
2021-02-08 08:28:32,871 DEBUG    Got a copy of environment <fiona._env.GDALEnv object at 0x0000005A71091948> options
2021-02-08 08:28:32,871 DEBUG    Credentialized: {'CHECK_WITH_INVERT_PROJ': True, 'GTIFF_IMPLICIT_JPEG_OVR': False, 'FIONA_ENV': True, 'GDAL_DATA': 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\gdal'}
2021-02-08 08:28:32,872 DEBUG    Exiting env context: <fiona.env.Env object at 0x0000005A70C7B548>
2021-02-08 08:28:32,873 DEBUG    Cleared existing <fiona._env.GDALEnv object at 0x0000005A71091948> options
2021-02-08 08:28:32,873 DEBUG    Stopping GDALEnv <fiona._env.GDALEnv object at 0x0000005A71091948>.
2021-02-08 08:28:32,873 DEBUG    Error handler popped.
2021-02-08 08:28:32,873 DEBUG    Stopped GDALEnv <fiona._env.GDALEnv object at 0x0000005A71091948>.
2021-02-08 08:28:32,873 DEBUG    Exiting outermost env
2021-02-08 08:28:32,873 DEBUG    Exited env context: <fiona.env.Env object at 0x0000005A70C7B548>
2021-02-08 08:28:32,873 DEBUG    Entering env context: <fiona.env.Env object at 0x0000005A70C7B548>
2021-02-08 08:28:32,873 DEBUG    Starting outermost env
2021-02-08 08:28:32,873 DEBUG    No GDAL environment exists
2021-02-08 08:28:32,873 DEBUG    New GDAL environment <fiona._env.GDALEnv object at 0x0000005A71091948> created
2021-02-08 08:28:32,873 DEBUG    Logging error handler pushed.
2021-02-08 08:28:32,874 DEBUG    All drivers registered.
2021-02-08 08:28:32,874 DEBUG    GDAL_DATA found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\gdal'.
2021-02-08 08:28:32,874 DEBUG    PROJ_LIB found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\proj'.
2021-02-08 08:28:32,874 DEBUG    Started GDALEnv <fiona._env.GDALEnv object at 0x0000005A71091948>.
2021-02-08 08:28:32,874 DEBUG    Updated existing <fiona._env.GDALEnv object at 0x0000005A71091948> with options {}
2021-02-08 08:28:32,874 DEBUG    Entered env context: <fiona.env.Env object at 0x0000005A70C7B548>
2021-02-08 08:28:32,874 DEBUG    Exiting env context: <fiona.env.Env object at 0x0000005A70C7B548>
2021-02-08 08:28:32,875 DEBUG    Cleared existing <fiona._env.GDALEnv object at 0x0000005A71091948> options
2021-02-08 08:28:32,875 DEBUG    Stopping GDALEnv <fiona._env.GDALEnv object at 0x0000005A71091948>.
2021-02-08 08:28:32,875 DEBUG    Error handler popped.
2021-02-08 08:28:32,875 DEBUG    Stopped GDALEnv <fiona._env.GDALEnv object at 0x0000005A71091948>.
2021-02-08 08:28:32,875 DEBUG    Exiting outermost env
2021-02-08 08:28:32,875 DEBUG    Exited env context: <fiona.env.Env object at 0x0000005A70C7B548>
2021-02-08 08:28:32,875 DEBUG    Flushed buffer
2021-02-08 08:28:32,875 DEBUG    Stopped session
2021-02-08 08:28:32,875 DEBUG    Entering env context: <fiona.env.Env object at 0x0000005A70C7B548>
2021-02-08 08:28:32,875 DEBUG    Starting outermost env
2021-02-08 08:28:32,875 DEBUG    No GDAL environment exists
2021-02-08 08:28:32,875 DEBUG    New GDAL environment <fiona._env.GDALEnv object at 0x0000005A71091A88> created
2021-02-08 08:28:32,875 DEBUG    Logging error handler pushed.
2021-02-08 08:28:32,876 DEBUG    All drivers registered.
2021-02-08 08:28:32,876 DEBUG    GDAL_DATA found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\gdal'.
2021-02-08 08:28:32,876 DEBUG    PROJ_LIB found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\proj'.
2021-02-08 08:28:32,876 DEBUG    Started GDALEnv <fiona._env.GDALEnv object at 0x0000005A71091A88>.
2021-02-08 08:28:32,876 DEBUG    Updated existing <fiona._env.GDALEnv object at 0x0000005A71091A88> with options {}
2021-02-08 08:28:32,877 DEBUG    Entered env context: <fiona.env.Env object at 0x0000005A70C7B548>
2021-02-08 08:28:32,877 DEBUG    Got a copy of environment <fiona._env.GDALEnv object at 0x0000005A71091A88> options
2021-02-08 08:28:32,877 DEBUG    Credentialized: {'CHECK_WITH_INVERT_PROJ': True, 'GTIFF_IMPLICIT_JPEG_OVR': False, 'FIONA_ENV': True, 'GDAL_DATA': 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\gdal'}
2021-02-08 08:28:32,877 DEBUG    Exiting env context: <fiona.env.Env object at 0x0000005A70C7B548>
2021-02-08 08:28:32,877 DEBUG    Cleared existing <fiona._env.GDALEnv object at 0x0000005A71091A88> options
2021-02-08 08:28:32,878 DEBUG    Stopping GDALEnv <fiona._env.GDALEnv object at 0x0000005A71091A88>.
2021-02-08 08:28:32,878 DEBUG    Error handler popped.
2021-02-08 08:28:32,878 DEBUG    Stopped GDALEnv <fiona._env.GDALEnv object at 0x0000005A71091A88>.
2021-02-08 08:28:32,878 DEBUG    Exiting outermost env
2021-02-08 08:28:32,878 DEBUG    Exited env context: <fiona.env.Env object at 0x0000005A70C7B548>
2021-02-08 08:28:32,878 DEBUG    Entering env context: <fiona.env.Env object at 0x0000005A70650948>
2021-02-08 08:28:32,878 DEBUG    Starting outermost env
2021-02-08 08:28:32,878 DEBUG    No GDAL environment exists
2021-02-08 08:28:32,878 DEBUG    New GDAL environment <fiona._env.GDALEnv object at 0x0000005A71091A88> created
2021-02-08 08:28:32,878 DEBUG    Logging error handler pushed.
2021-02-08 08:28:32,879 DEBUG    All drivers registered.
2021-02-08 08:28:32,879 DEBUG    GDAL_DATA found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\gdal'.
2021-02-08 08:28:32,879 DEBUG    PROJ_LIB found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\proj'.
2021-02-08 08:28:32,879 DEBUG    Started GDALEnv <fiona._env.GDALEnv object at 0x0000005A71091A88>.
2021-02-08 08:28:32,879 DEBUG    Updated existing <fiona._env.GDALEnv object at 0x0000005A71091A88> with options {}
2021-02-08 08:28:32,879 DEBUG    Entered env context: <fiona.env.Env object at 0x0000005A70650948>
2021-02-08 08:28:32,879 DEBUG    Index: 0
2021-02-08 08:28:32,888 DEBUG    Output nodata value read from file: nan
2021-02-08 08:28:32,888 DEBUG    Output nodata values: [nan]
2021-02-08 08:28:32,888 DEBUG    all_valid: False
2021-02-08 08:28:32,888 DEBUG    mask_flags: ([<MaskFlags.nodata: 8>],)
2021-02-08 08:28:32,890 DEBUG    Sharing flag: 0
2021-02-08 08:28:32,891 DEBUG    Nodata success: 1, Nodata value: nan
2021-02-08 08:28:32,891 DEBUG    Dataset <open DatasetBase name='<VRTDataset rasterXSize="3589" rasterYSize="2743"><SRS>PROJCS["WGS 84 / UTM zone 34N",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",21],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","32634"]]</SRS><GeoTransform>438363.722651493,25.0,0.0,4525499.363685054,0.0,-25.0</GeoTransform><VRTRasterBand band="1" dataType="Float32"><NoDataValue>nan</NoDataValue><ColorInterp>Gray</ColorInterp><ComplexSource><SourceFilename relativeToVRT="1">dummy.tif</SourceFilename><SourceBand>1</SourceBand><SourceProperties BlockXSize="3588" BlockYSize="1" RasterXSize="3589" RasterYSize="2743" dataType="Float32" /><SrcRect xOff="0" xSize="1" yOff="0" ySize="1" /><DstRect xOff="0" xSize="1" yOff="0" ySize="1" /><ScaleRatio>0</ScaleRatio><ScaleOffset>nan</ScaleOffset></ComplexSource><ComplexSource><SourceFilename relativeToVRT="0">C:\Users\Mouris\Desktop\Python\Python_Sebastian\Python-Course-Project\Results\Snow_end_month\snow_end_month18_1.tif</SourceFilename><SourceBand>1</SourceBand><SourceProperties BlockXSize="3588" BlockYSize="1" RasterXSize="3589" RasterYSize="2743" dataType="Float32" /><SrcRect xOff="0" xSize="3588" yOff="0" ySize="2742" /><DstRect xOff="-787.0" xSize="3588.0" yOff="-708.0" ySize="2742.0" /><NODATA>nan</NODATA></ComplexSource></VRTRasterBand></VRTDataset>' mode='r'> is started.
2021-02-08 08:28:32,891 DEBUG    Entering env context: <rasterio.env.Env object at 0x0000005A6FDBFAC8>
2021-02-08 08:28:32,891 DEBUG    Starting outermost env
2021-02-08 08:28:32,891 DEBUG    No GDAL environment exists
2021-02-08 08:28:32,891 DEBUG    New GDAL environment <rasterio._env.GDALEnv object at 0x0000005A01098E08> created
2021-02-08 08:28:32,892 DEBUG    GDAL_DATA found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\gdal'.
2021-02-08 08:28:32,892 DEBUG    PROJ_LIB found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\proj'.
2021-02-08 08:28:32,892 DEBUG    Started GDALEnv <rasterio._env.GDALEnv object at 0x0000005A01098E08>.
2021-02-08 08:28:32,892 DEBUG    Entered env context: <rasterio.env.Env object at 0x0000005A6FDBFAC8>
2021-02-08 08:28:32,892 DEBUG    IO window xoff=0.0 yoff=0.0 width=2801.0 height=2034.0
2021-02-08 08:28:33,006 DEBUG    Exiting env context: <rasterio.env.Env object at 0x0000005A6FDBFAC8>
2021-02-08 08:28:33,006 DEBUG    Cleared existing <rasterio._env.GDALEnv object at 0x0000005A01098E08> options
2021-02-08 08:28:33,006 DEBUG    Stopped GDALEnv <rasterio._env.GDALEnv object at 0x0000005A01098E08>.
2021-02-08 08:28:33,007 DEBUG    Exiting outermost env
2021-02-08 08:28:33,007 DEBUG    Exited env context: <rasterio.env.Env object at 0x0000005A6FDBFAC8>
2021-02-08 08:28:33,010 DEBUG    Entering env context: <rasterio.env.Env object at 0x0000005A01098D88>
2021-02-08 08:28:33,010 DEBUG    Starting outermost env
2021-02-08 08:28:33,010 DEBUG    No GDAL environment exists
2021-02-08 08:28:33,010 DEBUG    New GDAL environment <rasterio._env.GDALEnv object at 0x0000005A01098E48> created
2021-02-08 08:28:33,011 DEBUG    GDAL_DATA found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\gdal'.
2021-02-08 08:28:33,011 DEBUG    PROJ_LIB found in environment: 'C:\\Users\\Mouris\\AppData\\Local\\Continuum\\anaconda3\\envs\\geo-python\\Library\\share\\proj'.
2021-02-08 08:28:33,012 DEBUG    Started GDALEnv <rasterio._env.GDALEnv object at 0x0000005A01098E48>.
2021-02-08 08:28:33,012 DEBUG    Entered env context: <rasterio.env.Env object at 0x0000005A01098D88>
2021-02-08 08:28:33,057 DEBUG    Exiting env context: <rasterio.env.Env object at 0x0000005A01098D88>
2021-02-08 08:28:33,057 DEBUG    Cleared existing <rasterio._env.GDALEnv object at 0x0000005A01098E48> options
2021-02-08 08:28:33,057 DEBUG    Stopped GDALEnv <rasterio._env.GDALEnv object at 0x0000005A01098E48>.
2021-02-08 08:28:33,057 DEBUG    Exiting outermost env
2021-02-08 08:28:33,057 DEBUG    Exited env context: <rasterio.env.Env object at 0x0000005A01098D88>
2021-02-08 08:28:33,208 DEBUG    Exiting env context: <fiona.env.Env object at 0x0000005A70650948>
2021-02-08 08:28:33,208 DEBUG    Cleared existing <fiona._env.GDALEnv object at 0x0000005A71091A88> options
2021-02-08 08:28:33,208 DEBUG    Stopping GDALEnv <fiona._env.GDALEnv object at 0x0000005A71091A88>.
2021-02-08 08:28:33,208 DEBUG    Error handler popped.
2021-02-08 08:28:33,208 DEBUG    Stopped GDALEnv <fiona._env.GDALEnv object at 0x0000005A71091A88>.
2021-02-08 08:28:33,208 DEBUG    Exiting outermost env
2021-02-08 08:28:33,208 DEBUG    Exited env context: <fiona.env.Env object at 0x0000005A70650948>
2021-02-08 08:28:33,208 DEBUG    Flushed buffer
2021-02-08 08:28:33,209 DEBUG    Stopped session
2021-02-08 08:28:33,276 DEBUG    Exited  main
